### ISSUE TITLE
Cancelling an event threw an 'Uncaught TypeError' of 'event::cancel()'

### ISSUE THREAD

**Issue by genonullfree** [trmalfurious/meetups.moe#1]
What we did:
I created an event to expire in a week and made a comment.
Someone else joined the event and made a comment.
I made another comment.
I cancelled the event.

`Fatal error: Uncaught TypeError: Return value of event::cancel() must be an instance of void, none returned in /var/www/html/events.php:113 Stack trace: #0 /var/www/html/e.php(37): event->cancel() #1 {main} thrown in /var/www/html/events.php on line 113`

**Comment by trmalfurious** [comment]
This should now be fixed.  No changeset related as this was an issue with the server installation.
